### ISSUE TITLE
gpt 서버의 오류로 응답에 실패했을 때 질문을 다시 입력해야해서 불편해요

### ISSUE THREAD

**Issue by drunkenhw** [teco-chat/frontend#14]
gpt가 서버오류로 응답을 하지 못할 때는 입력창에 이전 질문이 남아있었으면 좋겠습니다 ![image](https://user-images.githubusercontent.com/106640954/236378558-e8702bd5-1942-4f5c-ae00-21aaf1c1efd1.png)

**Comment by greeng00se** [comment]
항상 감사합니다 박스터
