### ISSUE TITLE
새로운 채팅 시작하기 버튼의 위치를 옮겨주세요

### ISSUE THREAD

**Issue by drunkenhw** [teco-chat/frontend#9]

**Comment by drunkenhw** [comment]
혹은 채팅 목록에 들어갔다가 다시 홈 화면에 들어갔을 때 스크롤을 제일 아래에 위치하게 해주세요

**Comment by greeng00se** [comment]
채팅 목록에 갔다가 홈화면 갈 때 기존 질문을 다 지워지도록 했고
채팅을 할 때, 이전 채팅을 선택할 때 스크롤이 자연스럽게 아래로 내려가도록 반영했습니다.
